/* PetZona · estrutura compartilhada entre HTML e Figma. Sem dependências. */
const PZ = (() => {
  const C = { baby:'#DDEDFA', plum:'#65416F', periwinkle:'#596D9E', lilac:'#DFD2EC', blue:'#BED7ED', ink:'#26364F', muted:'#596477', white:'#FFFFFF', line:'#CAD2DF', surface:'#F6F8FC', green:'#25634B', greenLight:'#E0F2E8' };
  const paths = {
    paw:'<ellipse cx="7" cy="7" rx="2.4" ry="3.1"/><ellipse cx="13" cy="5" rx="2.4" ry="3.1"/><ellipse cx="19" cy="8" rx="2.4" ry="3.1"/><ellipse cx="3" cy="13" rx="2" ry="2.7"/><path d="M7 16c1-6 7-7 10-2 6 8-1 8-5 6-5 3-9 1-5-4Z"/>',
    home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',
    search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',
    cart:'<path d="M2 3h3l3 13h11l3-9H6"/><circle cx="9" cy="21" r="1"/><circle cx="18" cy="21" r="1"/>',
    arrow:'<path d="m14 5-7 7 7 7M7 12h14"/>',
    chevron:'<path d="m9 5 7 7-7 7"/>',
    check:'<path d="m4 12 5 5L20 6"/>',
    heart:'<path d="M12 21 3 12C-3 4 7-1 12 6c5-7 15-2 9 6Z"/>',
    bag:'<path d="M4 7h16l1 15H3ZM8 7V5a4 4 0 0 1 8 0v2"/>',
    calendar:'<rect x="3" y="5" width="18" height="17" rx="3"/><path d="M7 2v6M17 2v6M3 11h18M7 15h3M14 15h3M7 18h3"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
    pin:'<path d="M19 9c0 6-7 13-7 13S5 15 5 9a7 7 0 0 1 14 0Z"/><circle cx="12" cy="9" r="2.5"/>',
    dog:'<path d="M7 7 3 4 1 13l5 3M17 7l4-3 2 9-5 3M6 8c0-6 12-6 12 0v8c0 8-12 8-12 0Z"/><path d="M9 11v1M15 11v1m-5 4 2 2 2-2m-2 2v2"/>',
    cat:'<path d="M4 10V2l6 5h4l6-5v8c5 16-21 16-16 0Z"/><path d="M8 13h1m6 0h1m-5 4h2M1 16l5 1m-5 3 5-1m12-2 5-1m-5 3 5 1"/>',
    bird:'<path d="M6 17C-1 3 14-1 17 7l5 4-5 1v5l-9 4-5-1ZM8 13l5-3M9 21v2m5-3v3"/><circle cx="13" cy="6" r=".5"/>',
    spa:'<path d="M12 20C1 20 2 10 2 10s6 0 10 5c4-5 10-5 10-5s1 10-10 10Zm0-5C5 9 12 2 12 2s7 7 0 13Z"/>',
    taxi:'<path d="m3 10 3-6h12l3 6v10H3ZM3 10h18M8 4V2h8v2M6 20v3m12-3v3M6 15h2m8 0h2"/>',
    bath:'<path d="M2 12h20v4c0 4-20 4-20 0ZM5 12V4c0-4 6-4 6 0M5 21v2m14-2v2M15 6h.1M19 4h.1m-1 5h.1"/>',
    medical:'<path d="M9 2h6v7h7v6h-7v7H9v-7H2V9h7Z"/>',
    walk:'<path d="M6 2v10l6 4 4 6M6 12l-3 9M6 6l8 6h7"/><circle cx="7" cy="2" r="1"/>',
    person:'<circle cx="12" cy="7" r="4"/><path d="M3 22v-3c0-8 18-8 18 0v3Z"/>',
    water:'<path d="M3 12h18v7c0 5-18 5-18 0ZM3 12c0-4 18-4 18 0M10 10V4c0-4 5-4 5 0v2m-3 4V4m3 3v2"/>',
    plus:'<path d="M12 4v16M4 12h16"/>',
    minus:'<path d="M4 12h16"/>',
    star:'<path d="m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z"/>',
    info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',
    card:'<rect x="2" y="4" width="20" height="16" rx="3"/><path d="M2 9h20M6 15h4"/>',
  };
  function svg(key, color=C.plum, size=24) { return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="${key==='paw'?color:'none'}" stroke="${color}" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${paths[key]||paths.paw}</svg>`; }
  const t=(text,size=16,weight=400,color='ink',extra={})=>({type:'text',text,size,weight,color,...extra});
  const col=(children,extra={})=>({type:'col',children,gap:12,...extra});
  const row=(children,extra={})=>({type:'row',children,gap:12,align:'center',...extra});
  const icon=(key,size=24,color='plum')=>({type:'icon',key,size,color,fixed:true});
  const btn=(text,action,extra={})=>({type:'button',text,action,kind:'primary',...extra});
  const card=(children,extra={})=>col(children,{bg:'white',border:'line',radius:20,pad:16,...extra});
  const field=(label,value,key,extra={})=>({type:'field',label,value,key,...extra});
  const art=(key,label,height=130,extra={})=>({type:'art',key,label,height,bg:'baby',...extra});
  const note=(text)=>row([icon('info',20,'periwinkle'),t(text,13,400,'muted')],{bg:'surface',pad:12,radius:12});
  const pill=(text,color='plum',bg='lilac')=>t(text,12,600,color,{bg,pad:7,radius:8,fixed:true});
  const price=v=>'R$ '+v.toFixed(2).replace('.',',');
  const products=[{id:'water',name:'Bebedouro automático',desc:'Água fresquinha ao longo do dia.',price:89.9,icon:'water',category:'Acessórios'},{id:'food',name:'Ração para cães adultos',desc:'Nutrição equilibrada • 1 kg',price:75.9,icon:'bag',category:'Alimentação'},{id:'toy',name:'Brinquedo para gatos',desc:'Mais estímulo e diversão.',price:29.9,icon:'cat',category:'Brinquedos'},{id:'bowl',name:'Comedouro para aves',desc:'Prático para a rotina do seu pet.',price:24.9,icon:'bird',category:'Acessórios'}];
  const services={bath:{name:'Banho e tosa',provider:'Marina Pet Care',price:70,icon:'bath',duration:'Aproximadamente 1h30',tag:'Higiene e bem-estar',description:'Cuidado tranquilo, da chegada à hora de buscar seu pet.',items:['Banho e secagem cuidadosa','Escovação e tosa higiênica','Atualização ao finalizar o atendimento']},spa:{name:'Spa Pet',provider:'PetZona Spa',price:90,icon:'spa',duration:'Diária • 8h às 18h',tag:'Um dia inteiro de carinho',description:'Para os dias em que sua rotina está cheia: atenção, descanso e companhia para o seu pet.',items:['Brincadeiras acompanhadas e carinho','Pausas para descanso e alimentação','Atualizações ao tutor durante o dia']},taxi:{name:'Táxi Pet',provider:'Táxi Pet Seguro',price:60,icon:'taxi',duration:'Trajeto de exemplo • 30 min',tag:'Transporte com cuidado',description:'Agende o transporte do seu pet para chegar ao destino com mais tranquilidade.',items:['Retirada no endereço combinado','Transporte com caixa ou cinto adequado','Aviso de chegada ao destino']}};
  const initial={route:'home',product:'water',qty:1,cartQty:0,service:'bath',date:'18',time:'11:30',pet:'Mel • Cachorro • Porte médio',payment:'Pix',taxiFrom:'Endereço de retirada',taxiTo:'PetZona • Unidade Centro',taxiReturn:false,notes:'',booked:false,booking:null,search:'',category:'Todos',filter:'Todos',showEmpty:false};
  function productCard(p) {return card([art(p.icon,p.category,108),t(p.name,15,600),t(price(p.price),18,700,'plum')],{pad:12,gap:8,action:'product:'+p.id,name:'Produto / '+p.name});}
  function serviceCard(key) {const s=services[key];return card([row([art(s.icon,'',72,{width:72}),col([t(s.name,18,700),t(s.tag,13,400,'muted'),t('A partir de '+price(s.price),14,600,'plum')],{gap:5}),icon('chevron',20)])],{action:'service:'+key,pad:14,name:'Serviço / '+s.name});}
  function bookingSummary(s,confirmed=false){const v=services[s.service];return card([row([art(v.icon,'',64,{width:64}),col([t(v.name,18,700),t(v.provider,14,400,'muted')],{gap:4})]),row([icon('calendar',20),t(s.date+' set 2026 • '+(s.service==='spa'?'8h às 18h':s.time),15,600)]),row([icon('paw',20),t(s.pet,14)]),row([icon('pin',20),t(s.service==='taxi'?s.taxiFrom+' → '+s.taxiTo:'PetZona • Unidade Centro',14)]),...(s.service==='taxi'&&s.taxiReturn?[t('Ida e volta • retorno às 18h',14,600,'plum')]:[]),row([t('Valor '+(confirmed?'reservado':'do serviço'),14),t(price(v.price*(s.service==='taxi'&&s.taxiReturn?2:1)),18,700,'plum')],{justify:'between'})],{gap:14});}
  function screen(s){
    const p=products.find(p=>p.id===((s.route==='cart'||s.route==='checkout'||s.route==='purchased')?(s.cartProduct||s.product):s.product))||products[0], v=services[s.service]||services.bath;
    const total=p.price*s.cartQty+15;
    const out={id:s.route,title:'',subtitle:'',nav:true,active:'home',back:'home',body:[],footer:[]};
    switch(s.route){
      case 'login':Object.assign(out,{title:'PetZona',nav:false,back:null,body:[art('paw','Mais vida para quem te faz bem.',180,{bg:'baby'}),t('O cuidado começa aqui.',30,700),t('Produtos e serviços para uma rotina mais leve com seu pet.',16,400,'muted'),field('E-mail','','email',{placeholder:'seuemail@exemplo.com',inputType:'email'}),field('Senha','','password',{placeholder:'Digite sua senha',inputType:'password'}),btn('Entrar','login'),btn('Explorar sem entrar','go:home',{kind:'secondary'}),note('Protótipo acadêmico: o acesso é demonstrativo. Não é necessário informar dados reais.') ]});break;
      case 'home':Object.assign(out,{title:'PetZona',back:null,body:[col([pill('BEM-VINDA AO PETZONA'),t('Olá, Tamiris!',30,700),t('Mais tempo para cuidar de quem você ama.',16,400,'muted')],{bg:'baby',pad:20,radius:22,gap:10}),btn('O que seu pet precisa?','go:products',{kind:'search',icon:'search'}),row([btn('Produtos','go:products',{icon:'bag'}),btn('Serviços','go:services',{kind:'secondary',icon:'paw'})]),row([t('Para todos os pets',19,700)],{gap:8}),row([card([icon('dog',32),t('Cães',14,600)],{align:'center',action:'category:Cães',pad:14}),card([icon('cat',32),t('Gatos',14,600)],{align:'center',action:'category:Gatos',pad:14}),card([icon('bird',32),t('Aves',14,600)],{align:'center',action:'category:Aves',pad:14})]),t('Queridinhos da rotina',19,700),row([productCard(products[0]),productCard(products[1])],{align:'stretch'}),card([row([icon('spa',28),col([t('Seu pet merece um dia de carinho',17,700),t('Conheça a diária do Spa Pet.',14,400,'muted')],{gap:4})]),btn('Conhecer o Spa Pet','service:spa',{kind:'secondary'})],{bg:'lilac',border:null})]});break;
      case 'products':{
        let list=products.filter(p=>(p.name+' '+p.category).toLocaleLowerCase('pt-BR').includes(s.search.toLocaleLowerCase('pt-BR')));
        if(s.category==='Cães')list=list.filter(p=>['water','food'].includes(p.id));
        if(s.category==='Gatos')list=list.filter(p=>['water','toy'].includes(p.id));
        if(s.category==='Aves')list=list.filter(p=>p.id==='bowl');
        Object.assign(out,{title:'Produtos',active:'products',body:[field('Buscar produtos',s.search,'search',{placeholder:'Ex.: bebedouro',search:true}),row(['Todos','Cães','Gatos','Aves'].map(c=>btn(c,'category:'+c,{kind:s.category===c?'primary':'chip',small:true})),{gap:6,wrap:true}),t(list.length+' produtos encontrados',14,400,'muted'),...(!list.length?[art('search','Nenhum produto encontrado',160),t('Tente buscar por outro nome.',18,600),btn('Limpar busca','clearSearch',{kind:'secondary'})]:[row(list.slice(0,2).map(productCard),{align:'stretch'}),...(list.length>2?[row(list.slice(2).map(productCard),{align:'stretch'})]:[])]),note('Acessórios, alimentação e brinquedos para cuidar da rotina do seu pet.')]});break;}
      case 'product':Object.assign(out,{title:'Detalhes do produto',back:'products',active:'products',body:[art(p.icon,p.category,210,{bg:'baby'}),pill(p.category),t(p.name,28,700),t(price(p.price),30,700,'plum'),t(p.desc,16,400,'muted'),card([t('Pensado para o dia a dia',17,700),t(p.id==='water'?'Reservatório removível e estrutura fácil de limpar. Consulte medidas e capacidade antes de comprar.':'Uma escolha prática para os cuidados do dia a dia. Confira as características na embalagem.',15,400,'muted')]),row([t('Quantidade',16,600),row([btn('−','qty:-1',{kind:'icon',label:'Diminuir quantidade'}),t(String(s.qty),17,600,'ink',{fixed:true}),btn('+','qty:1',{kind:'icon',label:'Aumentar quantidade'})],{fixed:true,gap:8})],{justify:'between'})],footer:[btn('Adicionar ao carrinho','addCart',{icon:'cart'})]});break;
      case 'cart':Object.assign(out,{title:'Meu carrinho',back:'products',active:'products',body:s.cartQty===0?[art('cart','Seu carrinho está vazio',180),t('Vamos encontrar algo para o seu pet?',25,700),t('Escolha um produto para continuar.',16,400,'muted'),btn('Explorar produtos','go:products')]:[card([row([art(p.icon,'',84,{width:84}),col([t(p.name,16,600),t(price(p.price),17,700,'plum')],{gap:6})]),row([btn('Remover','removeCart',{kind:'chip'}),row([btn('−','cartQty:-1',{kind:'icon',label:'Diminuir quantidade no carrinho'}),t(String(s.cartQty),16,600,'ink',{fixed:true}),btn('+','cartQty:1',{kind:'icon',label:'Aumentar quantidade no carrinho'})],{fixed:true,gap:8})],{justify:'between'})]),card([row([icon('pin'),col([t('Entrega no seu endereço',16,600),t('Prazo estimado: 3 a 6 dias úteis',14,400,'muted')],{gap:4})])]),t('Resumo da compra',20,700),card([row([t('Produtos'),t(price(p.price*s.cartQty),16,600)],{justify:'between'}),row([t('Entrega'),t(price(15),16,600)],{justify:'between'}),{type:'line'},row([t('Total',18,700),t(price(total),23,700,'plum')],{justify:'between'})]),note('Valores e prazos ilustrativos para avaliação do fluxo.')],footer:s.cartQty?[btn('Continuar para pagamento','go:checkout')]:[]});break;
      case 'checkout':Object.assign(out,{title:'Finalizar compra',back:'cart',active:'products',body:[pill('ETAPA FINAL'),t('Onde vamos entregar?',23,700),field('Endereço de entrega',s.address||'Rua Exemplo, 123 • Centro','address'),t('Como deseja pagar?',20,700),row([btn('Pix','payment:Pix',{kind:s.payment==='Pix'?'primary':'secondary',icon:'check'}),btn('Cartão','payment:Cartão',{kind:s.payment==='Cartão'?'primary':'secondary',icon:'card'})]),note(s.payment==='Pix'?'Nesta demonstração, o pedido é concluído sem gerar uma cobrança Pix.':'Nesta demonstração, nenhum número de cartão é solicitado.'),card([t('Seu pedido',18,700),t(p.name+' × '+Math.max(1,s.cartQty),15),row([t('Produtos'),t(price(p.price*Math.max(1,s.cartQty)),16,600)],{justify:'between'}),row([t('Entrega'),t(price(15),16,600)],{justify:'between'}),{type:'line'},row([t('Total',18,700),t(price(p.price*Math.max(1,s.cartQty)+15),24,700,'plum')],{justify:'between'})])],footer:[btn('Concluir compra demonstrativa','go:purchased')]});break;
      case 'purchased':Object.assign(out,{title:'Pedido realizado',active:'products',body:[art('check','Tudo certo!',150,{bg:'greenLight',color:'green'}),t('Seu pedido foi registrado.',28,700),t('Uma compra de exemplo, para testar a experiência.',16,400,'muted'),card([t(p.name,18,600),t('Quantidade: '+Math.max(1,s.cartQty),15),t('Total: '+price(p.price*Math.max(1,s.cartQty)+15),20,700,'plum'),t('Entrega estimada: 3 a 6 dias úteis',15,400,'muted')]),btn('Voltar ao início','go:home')]});break;
      case 'services':Object.assign(out,{title:'Serviços',active:'services',body:[col([pill('CUIDADO QUE ACOLHE'),t('Carinho em cada detalhe.',28,700),t('Encontre o cuidado que combina com a rotina do seu pet.',16,400,'muted')],{bg:'baby',pad:20,radius:22}),serviceCard('bath'),serviceCard('spa'),serviceCard('taxi'),btn('Ver todos os profissionais','go:professionals',{kind:'secondary'}),note('Spa Pet inclui companhia durante o dia. Táxi Pet pode ser agendado separadamente.') ]});break;
      case 'professionals':Object.assign(out,{title:'Profissionais',back:'services',active:'services',body:[t('Encontre o cuidado ideal',24,700),row(['Todos','Banho','Spa','Táxi'].map(f=>btn(f,'filter:'+f,{kind:s.filter===f?'primary':'chip',small:true})),{gap:6,wrap:true}),...Object.keys(services).filter(k=>s.filter==='Todos'||({Banho:'bath',Spa:'spa','Táxi':'taxi'}[s.filter]===k)).map(k=>{const v=services[k];return card([row([art(v.icon,'',76,{width:76}),col([t(v.provider,18,700),t(v.name,14,400,'muted'),t('A partir de '+price(v.price),15,600,'plum')],{gap:6}),icon('chevron',18)]),row([icon('pin',16),t('Unidade Centro • Exemplo',13,400,'muted')],{gap:6})],{action:'service:'+k});}),note('Prestadores e preços são dados demonstrativos do protótipo.') ]});break;
      case 'provider':Object.assign(out,{title:'Conheça o serviço',back:'professionals',active:'services',body:[art(v.icon,v.tag,160),t(v.provider,28,700),pill(v.name),t(v.description,16,400,'muted'),row([icon('clock',20),t(v.duration,15,600)]),t('O que está incluído',20,700),card(v.items.map(txt=>row([icon('check',20),t(txt,15)])),{gap:16}),...(s.service==='spa'?[note('Informe a rotina de alimentação e os cuidados específicos do pet no agendamento.')]:[]),row([t(s.service==='taxi'?'Ida • trajeto de exemplo':'A partir de',14,400,'muted'),t(price(v.price),26,700,'plum')],{justify:'between'})],footer:[btn(s.service==='spa'?'Reservar diária':s.service==='taxi'?'Agendar transporte':'Agendar cuidado','go:booking')]});break;
      case 'booking':Object.assign(out,{title:s.service==='spa'?'Reservar Spa Pet':s.service==='taxi'?'Agendar Táxi Pet':'Agendar banho e tosa',back:'provider',active:'services',body:[row([icon(v.icon,28),col([t(v.provider,18,700),t(v.duration,14,400,'muted')],{gap:4})]),{type:'select',label:'Qual pet receberá o cuidado?',key:'pet',value:s.pet,options:['Mel • Cachorro • Porte médio','Luna • Gato • Porte pequeno']},t('Escolha o dia',20,700),t('Setembro de 2026',15,600,'muted'),row(['18','19','21','22'].map((d,i)=>btn(['Sex','Sáb','Seg','Ter'][i]+' '+d,'date:'+d,{kind:s.date===d?'primary':'secondary',small:true})),{gap:8,wrap:true}),...(s.service==='spa'?[card([row([icon('clock'),col([t('Diária completa',17,700),t('Entrada às 8h • saída às 18h',14,400,'muted')],{gap:4})])],{bg:'baby',border:null})]:[t('Horário de '+(s.service==='taxi'?'retirada':'atendimento'),18,700),row(['09:00','11:30','14:00'].map(h=>btn(h,'time:'+h,{kind:s.time===h?'primary':'secondary',small:true})),{gap:8,wrap:true})]),...(s.service==='taxi'?[field('Local de retirada',s.taxiFrom,'taxiFrom'),field('Destino',s.taxiTo,'taxiTo'),btn(s.taxiReturn?'✓ Ida e volta • retorno às 18h':'Adicionar volta • retorno às 18h','toggleReturn',{kind:'secondary'})]:[card([row([icon('pin'),col([t('Atendimento no PetZona',16,600),t('Unidade Centro • Endereço de exemplo',13,400,'muted')],{gap:4})])])]),field(s.service==='spa'?'Rotina e cuidados do seu pet':'Alguma observação?',s.notes,'notes',{placeholder:s.service==='spa'?'Alimentação, adaptação, descanso...':'Conte o que precisamos saber',multiline:true}),row([t('Total',18,700),t(price(v.price*(s.service==='taxi'&&s.taxiReturn?2:1)),24,700,'plum')],{justify:'between'}),note('Você poderá revisar e alterar a reserva nesta demonstração.')],footer:[btn('Confirmar agendamento','book')]});break;
      case 'confirmation':{
        const q=s.booking||s,service=services[q.service];
        Object.assign(out,{title:'Agendamento',active:'services',back:'services',body:[art('check','Agendamento confirmado!',120,{bg:'greenLight',color:'green'}),t('Seu pet está em boas mãos.',25,700),bookingSummary(q,true),card([row([icon('check',20,'green'),col([t('Confirmado',16,700,'green'),t('Reserva registrada para '+q.date+' de setembro.',13,400,'muted')],{gap:4})]),row([icon('clock',20,'muted'),col([t(q.service==='taxi'?'Aguardando retirada':'Aguardando a chegada do pet',15,600),t('As próximas etapas aparecerão aqui.',13,400,'muted')],{gap:4})])]),btn('Alterar agendamento','editBooking',{kind:'secondary'}),btn('Voltar ao início','go:home',{kind:'chip'})]});break;}
      default:return screen({...s,route:'home'});
    }
    return out;
  }
  const frameSpecs=[['login','00 · Login'],['home','01 · Início'],['products','02 · Produtos'],['product','03 · Produto'],['cart','04 · Carrinho'],['checkout','05 · Pagamento'],['services','06 · Serviços'],['professionals','07 · Profissionais'],['provider','08 · Perfil do profissional'],['booking','09 · Agendamento'],['confirmation','10 · Confirmação'],['purchased','Extra · Compra concluída'],...['spa','taxi'].flatMap(k=>[['provider','08 · '+services[k].name,k],['booking','09 · '+services[k].name,k],['confirmation','10 · '+services[k].name,k]])];
  function frameState(spec){return {...initial,route:spec[0],service:spec[2]||'bath',cartQty:1};}
  return {C,svg,t,col,row,icon,btn,card,field,art,price,products,services,initial,screen,frameSpecs,frameState};
})();
